shallow_clone: true

os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2015
  - TOOLSET: vs2017

configuration:
  - Debug
  - Release
  - Retail

install:
  - git clone --depth 1 https://github.com/milostosic/build ..\build
  - git clone --depth 1 https://github.com/milostosic/rapp  ..\rapp
  - git clone --depth 1 https://github.com/milostosic/enkiTS  ..\enkiTS
  - git clone --depth 1 https://github.com/unittest-cpp/unittest-cpp.git ..\unittest-cpp
  - ..\build\tools\bin\windows\genie --file=genie\genie.lua %TOOLSET%

build:
  project: ../.build/windows/$(TOOLSET)/rbase/projects/rbase.sln
