
environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Debug

    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Release

    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      configuration: Retail

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      buildcfg: debug64

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      buildcfg: release64

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      buildcfg: retail64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
      buildcfg: debug64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
      buildcfg: release64

    - job_name: OSX
      APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
      buildcfg: retail64
    
shallow_clone: true

for:
  
# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
  
    init:
      - git clone --depth 1 https://github.com/RudjiGames/build build
      - git clone --depth 1 https://github.com/RudjiGames/rbase rbase
      - git clone --depth 1 https://github.com/unittest-cpp/unittest-cpp.git unittest-cpp
     
    install:
      - build\tools\bin\windows\genie.exe --file=rbase\genie\genie.lua vs2022
      
    build:
      project: ../.build/windows/vs2022/rbase/projects/rbase.sln

# ======================================
# Linux
# ======================================
  -
    matrix:
      only:
      - job_name: Linux

    init:
      - git clone --depth 1 https://github.com/RudjiGames/build build
      - git clone --depth 1 https://github.com/RudjiGames/rbase rbase
      - git clone --depth 1 https://github.com/bkaradzic/GENie GENie		# build GENie from source: `GLIBC_2.29' not found
      - git clone --depth 1 https://github.com/unittest-cpp/unittest-cpp.git unittest-cpp
      - cd GENie && make && cd ..

    install:
      - ./GENie/bin/linux/genie --file=rbase/genie/genie.lua --gcc=linux-gcc gmake
  
    build_script:
      - cd ./.build/linux/linux-gcc/rbase/projects/
      - make config=${buildcfg}

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - git clone --depth 1 https://github.com/RudjiGames/build build
      - git clone --depth 1 https://github.com/RudjiGames/rbase rbase
      - git clone --depth 1 https://github.com/bkaradzic/GENie GENie  # build GENie from source: we don't know the target CPU, can't use ARM binary from 'build'
      - git clone --depth 1 https://github.com/unittest-cpp/unittest-cpp.git unittest-cpp
      - cd GENie && make && cd ..
    
    install:
      - ./GENie/bin/darwin/genie --file=rbase/genie/genie.lua --gcc=osx-x64 gmake
    
    build_script:
      - cd ./.build/osx/clang/rbase/projects/
      - make config=${buildcfg}
